services:
  - type: static
    name: runhouston-main
    buildCommand: npm ci && npm run build:main
    staticPublishPath: dist/main
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: VITE_API_BASE
        value: https://run-houston-api.onrender.com
      - key: VITE_APP_TYPE
        value: main
      - key: VITE_APP_NAME
        value: Run Houston
      - key: VITE_APP_VERSION
        value: 1.0.1
      - key: VITE_ENVIRONMENT
        value: production
      - key: VITE_API_VERSION
        value: v1.0.0
